/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.MusicaLogica;
import java.net.URL;
import java.util.ArrayList;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author Bryan
 */
public class Ver extends javax.swing.JFrame {

    public String archi, name = "yolo";
    URL direcion;
    Player reproductor;

    public Ver() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    public void config(String tipo, String nombre) {
        archi = tipo;
        name = nombre;
        if (tipo.equals("Musica")) {
            lblPreview.setVisible(false);
            txtCanciones.setVisible(true);
            lblInfo.setText("Canciones del disco " + nombre + ":");
            ArrayList busqueda = new ArrayList();
            busqueda = MusicaLogica.canciones(nombre);
            String[] songs = busqueda.get(4).toString().split(",");
            for (int i = 0; i < songs.length; i++) {
                if (songs.length == i + 1) {
                    String song = Character.toString(songs[i].charAt(1));
                    txtCanciones.setText(txtCanciones.getText() + song + "\n");
                } else if (songs[i].length() <= 2) {
                    String song = Character.toString(songs[i].charAt(1));
                    txtCanciones.setText(txtCanciones.getText() + song + "\n");
                }
            }

        } else if (tipo.equals("Pelicula")) {
            txtCanciones.setVisible(false);
            lblPreview.setVisible(true);
            lblInfo.setText("Trailer de " + nombre + ":");
        }
    }

    public void cancion() {
        int a = 5;
        while (a <= 10) {
            try {
                FileInputStream fis;
                Player player;
                fis = new FileInputStream(name + ".mp3");
                BufferedInputStream bis = new BufferedInputStream(fis);
                player = new Player(bis);
                player.play();
            } catch (JavaLayerException | FileNotFoundException e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPreview = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCanciones = new javax.swing.JTextArea();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 153));
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 310, 19));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 196, 90, -1));

        txtCanciones.setEditable(false);
        txtCanciones.setColumns(20);
        txtCanciones.setRows(5);
        jScrollPane1.setViewportView(txtCanciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 153));

        btnPlay.setText("Reproducir");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 196, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        if (archi.equals("Musica")) {
            cancion();
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JTextArea txtCanciones;
    // End of variables declaration//GEN-END:variables
}
